services:
  app:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_API_URL_DASH: ${VITE_API_URL_DASH}
    image: ${PROJECT_NAME}-app
    container_name: ${PROJECT_NAME}-app
    restart: unless-stopped
    ports:
      - "3000:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
    networks: [web]  


networks:
  web:
    driver: bridge